# fly.toml app configuration file generated for the-interactive-gallery

app = "the-interactive-gallery"
primary_region = "lhr"  # London region, change if needed

[build]

[env]
  # Non-sensitive environment variables
  NODE_ENV = "production"
  PORT = "8080"  # Fly.io typically uses port 8080 internally
  UNSPLASH_BASE_URL = "https://api.unsplash.com"
  RATE_LIMIT_WINDOW_MS = "900000"
  RATE_LIMIT_MAX_REQUESTS = "100"
  CORS_ORIGINS = "https://the-interactive-gallery-zeta.vercel.app,http://localhost:3000"
  FRONTEND_URL = "https://the-interactive-gallery-zeta.vercel.app"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "5s"
    interval = "10s"
    method = "GET"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"

[machine]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  release_command = "npm run build && npm run migrate"  # Build TypeScript and run migrations

[processes]
  app = "npm start"  # Runs: node dist/server.js